package com.dnn.netty.server.responseWorks;

public enum ResCommand {
    RECEIVE_LIST_OF_FILES,

    LOGIN_WAS_CHANGED,
    LOGIN_WAS_NOT_CHANGED_DOU_TO_ERROR,
    LOGIN_IS_ALREADY_TAKEN,

    NICKNAME_WAS_CHANGED,
    NICKNAME_WAS_NOT_CHANGED,

    PASSWORD_WAS_CHANGED,
    PASSWORD_WAS_NOT_CHANGED,

    FILE_WAS_DELETED_SUCCESSFULLY,
    ERROR_DELETING_FILE,

    WRONG_LOGIN_OR_PASSWORD,
    USER_IS_EXIST,

    SUCCESSFUL_REGISTRATION,
    USER_HAS_EXISTED,

    RECEIVE_FILE,
    FILE_WAS_NOT_FOUND,
    HI,

    FOLDER_WAS_ADDED_SUCCESSFULLY,

    FILE_WAS_RECEIVED_SUCCESSFULLY,
    EXCEPTION_WHILE_RECEIVING_OF_THE_FILE,
    UNKNOWN_REQUEST,


}
